name: "Deploy Flux Host application"
description: "Deploy an application to Flux Host"

inputs:
  token:
    description: "A Flux Host System API JWT"
    required: true
  cluster-name:
    description: "The name of the cluster to deploy the application to"
    required: true
  application-name:
    description: "The name of the application"
    required: true
  metadata-json:
    description: "The json output of the docker/metadata-action"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
